backend:
  name: github
  repo: Sirc13/SchoolMusei
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Страницы"
    label_singular: "Страница"
    files:
      - name: "index"
        label: "Главная страница"
        file: "index.html"
        fields:
          - { label: "Содержание", name: "body", widget: "markdown", modes: ["code"] }

      - name: "about"
        label: "О нас"
        file: "project/about.html"
        fields:
          - { label: "Содержание", name: "body", widget: "markdown", modes: ["code"] }